from django.db import models

class Data(models.Model):
    id_region = models.IntegerField(blank=True, null=True)
    region = models.TextField(blank=True, null=True)
    id_delegation = models.IntegerField(blank=True, null=True)
    delegation = models.TextField(blank=True, null=True)
    code = models.TextField(blank=True, null=True)
    nom = models.TextField(blank=True, null=True)
    date_construction = models.DateTimeField(blank=True, null=True)
    tel = models.TextField(blank=True, null=True)
    fax = models.TextField(blank=True, null=True)
    id_province = models.IntegerField(blank=True, null=True)
    addresse = models.TextField(blank=True, null=True)
    id_str_superv = models.IntegerField(blank=True, null=True)
    id_responsable = models.IntegerField(blank=True, null=True)
    milieu = models.TextField(blank=True, null=True)
    superficie = models.FloatField(blank=True, null=True)
    propriete = models.TextField(blank=True, null=True)
    utilisation = models.TextField(blank=True, null=True)
    etat = models.TextField(blank=True, null=True)
    date_saisie = models.DateTimeField(blank=True, null=True)
    date_modif = models.DateTimeField(blank=True, null=True)
    id_commune = models.IntegerField(blank=True, null=True)
    latitude = models.FloatField(blank=True, null=True)
    longitude = models.FloatField(blank=True, null=True)
    type_centre = models.TextField(blank=True, null=True)
    nb_prn = models.IntegerField(blank=True, null=True)
    nb_sec = models.IntegerField(blank=True, null=True)
    nb_aux = models.IntegerField(blank=True, null=True)
    capacite = models.IntegerField(blank=True, null=True)
    date_ouvert_act = models.DateTimeField(blank=True, null=True)
    date_cessation = models.DateTimeField(blank=True, null=True)
    superficie_ac = models.FloatField(blank=True, null=True)
    gestion = models.TextField(blank=True, null=True)
    association = models.TextField(blank=True, null=True)
    activite = models.TextField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    id_service = models.IntegerField(blank=True, null=True)
    sous_categorie = models.TextField(blank=True, null=True)
    type_activite = models.TextField(blank=True, null=True)
    methode_calcul_benef = models.TextField(blank=True, null=True)
    programme = models.TextField(blank=True, null=True)
    sousaxe = models.TextField(blank=True, null=True)
    axe = models.TextField(blank=True, null=True)
    categorie = models.TextField(blank=True, null=True)
    categorie2 = models.TextField(blank=True, null=True)
    abrev = models.TextField(blank=True, null=True)
    cat = models.TextField(db_column='CAT', blank=True, null=True)  # Field name made lowercase.
    cat_programme = models.TextField(blank=True, null=True)
    id_structure = models.IntegerField(blank=True, null=True)
    id_centre = models.IntegerField(blank=True, null=True)
    id_activite = models.IntegerField(blank=True, null=True)
    id_periodicite = models.IntegerField(blank=True, null=True)
    nb_beneficiaires_m = models.FloatField(blank=True, null=True)
    nb_beneficiaires_f = models.FloatField(blank=True, null=True)
    nb_pers_entraide_tit = models.FloatField(blank=True, null=True)
    nb_pers_entraide_vac = models.FloatField(blank=True, null=True)
    nb_pers_entraide_vol = models.FloatField(blank=True, null=True)
    nb_pers_part = models.FloatField(blank=True, null=True)
    nb_pers_prom = models.FloatField(blank=True, null=True)
    nb_apparition = models.IntegerField(blank=True, null=True)
    nb_centres = models.IntegerField(blank=True, null=True)
    nb_beneficiaires_t = models.FloatField(blank=True, null=True)
    fact_ben = models.IntegerField(blank=True, null=True)
    nb_count = models.IntegerField(blank=True, null=True)
    taux_pauvre_reg = models.FloatField(blank=True, null=True)
    taux_pauvre_prov = models.FloatField(blank=True, null=True)
    taux_pauvre_comm = models.FloatField(blank=True, null=True)
    commune = models.TextField(blank=True, null=True)
    priorite = models.IntegerField(blank=True, null=True)
    personnes_cibles = models.TextField(blank=True, null=True)
    fcs = models.IntegerField(blank=True, null=True)
    categorie2aux = models.TextField(blank=True, null=True)
    axe_updated = models.CharField(max_length=100, blank=True, null=True)
    programme_updated = models.CharField(max_length=255, blank=True, null=True)


    class Meta:
        managed = False
        db_table = 'data'

class Historique(models.Model):
    cat_programme = models.CharField(max_length=16, blank=True, null=True)
    nb_centre = models.CharField(max_length=5, blank=True, null=True)
    nb_beneficiaires_t = models.CharField(max_length=7, blank=True, null=True)
    id_periodicite = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'historique'
                                                                                                                                