# Generated by Django 5.1.6 on 2025-07-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.TextField(blank=True, null=True)),
                ('delegation', models.TextField(blank=True, null=True)),
                ('nom', models.TextField(blank=True, null=True)),
                ('milieu', models.TextField(blank=True, null=True)),
                ('propriete', models.TextField(blank=True, null=True)),
                ('capacite', models.IntegerField(blank=True, null=True)),
                ('id_centre', models.TextField(blank=True, null=True)),
                ('nb_centres', models.IntegerField(blank=True, null=True)),
                ('id_periodicite', models.IntegerField(blank=True, null=True)),
                ('id_delegation', models.IntegerField(blank=True, null=True)),
                ('id_region', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'centre',
                'managed': False,
            },
        ),
    ]
