# Generated by Django 5.1.6 on 2025-09-11 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_activite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'managed': True},
        ),
    ]
