# Generated by Django 5.1.6 on 2025-09-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_data_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='axe_updated',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='programme_updated',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
