# Generated by Django 5.1.6 on 2025-09-23 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_data_axe_updated_data_programme_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'managed': False},
        ),
    ]
