# Generated by Django 5.1.6 on 2025-09-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie2', models.TextField(blank=True, null=True)),
                ('nb_centres', models.TextField(blank=True, null=True)),
                ('nb_beneficiaires_m', models.TextField(blank=True, db_column='nb_beneficiaires_m', null=True)),
                ('nb_beneficiaires_f', models.TextField(blank=True, db_column='nb_beneficiaires_f', null=True)),
                ('nb_beneficiaires_t', models.TextField(blank=True, db_column='nb_beneficiaires_t', null=True)),
                ('id_periodicite', models.TextField(blank=True, null=True)),
                ('region', models.TextField(blank=True, null=True)),
                ('delegation', models.TextField(blank=True, null=True)),
                ('id_region', models.IntegerField(blank=True, null=True)),
                ('id_delegation', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'activite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.TextField(blank=True, null=True)),
                ('delegation', models.TextField(blank=True, null=True)),
                ('cat_programme', models.TextField(blank=True, null=True)),
                ('nb_centres', models.IntegerField(blank=True, null=True)),
                ('nb_benef_m', models.IntegerField(blank=True, db_column='nb_benef_M', null=True)),
                ('nb_benef_f', models.IntegerField(blank=True, db_column='nb_benef_F', null=True)),
                ('nb_benef_t', models.IntegerField(blank=True, db_column='nb_benef_T', null=True)),
                ('id_periodicite', models.IntegerField(blank=True, null=True)),
                ('id_region', models.TextField(blank=True, null=True)),
                ('id_delegation', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'programme',
                'managed': False,
            },
        ),
    ]
